// قائمة الوظائف (للفلترة)
export const JOB_OPTIONS = [
  { id: "all", label: "كل الوظائف" },
  { id: "technical_manager", label: "مدير تقني" },
  { id: "track_head", label: "رئيس مسار" },
  { id: "academic_reviewer", label: "مراجع أكاديمي" },
  { id: "ops_planner", label: "مخطط عمليات" },
  { id: "quality_reviewer", label: "مراجع جودة" },
  { id: "admin", label: "المشرف العام" },
];

// قائمة التركات/المسارات (للفلترة)
export const TRACK_OPTIONS = [
  { id: "all", label: "كل التركات" },
  { id: "tech", label: "مسار تقني" },
  { id: "education", label: "مسار تعليمي" },
  { id: "content", label: "مسار المحتوى" },
  { id: "ops", label: "مسار العمليات" },
];

// قائمة الحالات (للفلترة)
export const STATUS_OPTIONS = [
  { id: "all", label: "كل الحالات" },
  { id: "in-progress", label: "قيد المراجعة" },
  { id: "accepted", label: "مقبول" },
  { id: "rejected", label: "مرفوض" },
];

// بيانات المتقدمين (Mock)
export const MOCK_APPLICANTS = [
  {
    id: "app_001",
    applicant: {
      name: "أحمد محمد",
      email: "ahmed.m@test.com",
      phone: "0512345678",
      idNumber: "1234567890",
      avatar: "أ",
    },
    jobRole: "technical_manager",
    jobTitle: "مدير تقني",
    track: "tech",
    status: "in-progress",
    currentStep: 2,
    appliedAt: "2025-03-15",
    steps: [
      { id: 1, status: "completed" },
      { id: 2, status: "active" },
      { id: 3, status: "pending" },
      { id: 4, status: "pending" },
      { id: 5, status: "pending" },
      { id: 6, status: "pending" },
    ],
    documents: {
      cv: { name: "Ahmed_CV.pdf", url: "#" },
      photo: { name: "ahmed_photo.jpg", url: "#" },
      idFront: { name: "id_front.jpg", url: "#" },
      idBack: { name: "id_back.jpg", url: "#" },
    },
    rejectionReason: "",
  },
  {
    id: "app_002",
    applicant: {
      name: "سارة علي",
      email: "sara.a@test.com",
      phone: "0523456789",
      idNumber: "2345678901",
      avatar: "س",
    },
    jobRole: "track_head",
    jobTitle: "رئيس مسار",
    track: "education",
    status: "in-progress",
    currentStep: 3,
    appliedAt: "2025-03-14",
    steps: [
      { id: 1, status: "completed" },
      { id: 2, status: "completed" },
      { id: 3, status: "completed" },
      { id: 4, status: "active" },
      { id: 5, status: "pending" },
      { id: 6, status: "pending" },
    ],
    documents: {
      cv: { name: "Sara_CV.pdf", url: "#" },
      photo: { name: "sara_photo.jpg", url: "#" },
      idFront: { name: "sara_id_front.jpg", url: "#" },
      idBack: { name: "sara_id_back.jpg", url: "#" },
    },
    rejectionReason: "",
  },
  {
    id: "app_003",
    applicant: {
      name: "خالد حسن",
      email: "khaled.h@test.com",
      phone: "0534567890",
      idNumber: "3456789012",
      avatar: "خ",
    },
    jobRole: "academic_reviewer",
    jobTitle: "مراجع أكاديمي",
    track: "content",
    status: "rejected",
    currentStep: 1,
    appliedAt: "2025-03-12",
    steps: [
      { id: 1, status: "completed" },
      { id: 2, status: "rejected" },
      { id: 3, status: "pending" },
      { id: 4, status: "pending" },
      { id: 5, status: "pending" },
      { id: 6, status: "pending" },
    ],
    documents: {
      cv: { name: "Khaled_CV.pdf", url: "#" },
      photo: { name: "khaled_photo.jpg", url: "#" },
      idFront: { name: "khaled_id_front.jpg", url: "#" },
      idBack: { name: "khaled_id_back.jpg", url: "#" },
    },
    rejectionReason: "السيرة الذاتية لا تتوافق مع متطلبات الوظيفة.",
  },
  {
    id: "app_004",
    applicant: {
      name: "منى إبراهيم",
      email: "mona.i@test.com",
      phone: "0545678901",
      idNumber: "4567890123",
      avatar: "م",
    },
    jobRole: "ops_planner",
    jobTitle: "مخطط عمليات",
    track: "ops",
    status: "accepted",
    currentStep: 5,
    appliedAt: "2025-03-10",
    steps: [
      { id: 1, status: "completed" },
      { id: 2, status: "completed" },
      { id: 3, status: "completed" },
      { id: 4, status: "completed" },
      { id: 5, status: "completed" },
      { id: 6, status: "active" },
    ],
    documents: {
      cv: { name: "Mona_CV.pdf", url: "#" },
      photo: { name: "mona_photo.jpg", url: "#" },
      idFront: { name: "mona_id_front.jpg", url: "#" },
      idBack: { name: "mona_id_back.jpg", url: "#" },
    },
    rejectionReason: "",
  },
  {
    id: "app_005",
    applicant: {
      name: "يوسف سعيد",
      email: "yousef.s@test.com",
      phone: "0556789012",
      idNumber: "5678901234",
      avatar: "ي",
    },
    jobRole: "quality_reviewer",
    jobTitle: "مراجع جودة",
    track: "content",
    status: "in-progress",
    currentStep: 0,
    appliedAt: "2025-03-16",
    steps: [
      { id: 1, status: "active" },
      { id: 2, status: "pending" },
      { id: 3, status: "pending" },
      { id: 4, status: "pending" },
      { id: 5, status: "pending" },
      { id: 6, status: "pending" },
    ],
    documents: {
      cv: { name: "Yousef_CV.pdf", url: "#" },
      photo: { name: "yousef_photo.jpg", url: "#" },
      idFront: { name: "yousef_id_front.jpg", url: "#" },
      idBack: { name: "yousef_id_back.jpg", url: "#" },
    },
    rejectionReason: "",
  },
];