export const MOCK_STUDENTS = [
  {
    id: 1,
    name: "محمد أحمد",
    email: "mohamed@example.com",
    course: "تطوير واجهات المستخدم",
    progress: 85,
    lastActive: "منذ ساعتين",
    grade: "A",
    assignments: 12,
    completedAssignments: 10,
  },
  {
    id: 2,
    name: "سارة خالد",
    email: "sara@example.com",
    course: "تطوير واجهات المستخدم",
    progress: 72,
    lastActive: "منذ 5 ساعات",
    grade: "B+",
    assignments: 12,
    completedAssignments: 9,
  },
  {
    id: 3,
    name: "عمر يوسف",
    email: "omar@example.com",
    course: "أساسيات JavaScript",
    progress: 60,
    lastActive: "أمس",
    grade: "B",
    assignments: 10,
    completedAssignments: 6,
  },
  {
    id: 4,
    name: "نورة سعيد",
    email: "noura@example.com",
    course: "تطوير واجهات المستخدم",
    progress: 95,
    lastActive: "منذ 30 دقيقة",
    grade: "A+",
    assignments: 12,
    completedAssignments: 12,
  },
  {
    id: 5,
    name: "خالد عمر",
    email: "khaled@example.com",
    course: "أساسيات JavaScript",
    progress: 40,
    lastActive: "منذ يومين",
    grade: "C+",
    assignments: 10,
    completedAssignments: 4,
  },
];
